### ISSUE TITLE
Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by alandtse** [custom-components/custom_updater#104]
## Version of the custom_component

4.2.13
## Describe the bug
Non-imported `__version__` not discovered when defined in [`__init__.py`](https://github.com/alandtse/custom_components/blob/custom_updater/alexa_media/__init__.py#L28). 
This may be caused by a relative import of .const for other imports. As noted before, I'm not hard-coding `custom_component` because my test suite will test it both as a `custom_component` or a `homeassistant.component`

```python
from .const import (
    ALEXA_COMPONENTS, CONF_DEBUG, CONF_ACCOUNTS, CONF_INCLUDE_DEVICES,
    CONF_EXCLUDE_DEVICES, DATA_ALEXAMEDIA, DOMAIN, MIN_TIME_BETWEEN_SCANS,
    MIN_TIME_BETWEEN_FORCED_SCANS, SCAN_INTERVAL
)
```
Shouldn't the regex search from the prior version be a fallback if the new import method fails?

## `custom_updater` configuration

```yaml
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/alandtse/custom_components/custom_updater/custom_components.json
```

## Resources in lovelace configuration

```yaml
resources:
  - type: module
    url: /customcards/github/custom-cards/tracker-card.js?track=true
```

## Tracker-card configuration

```yaml

      - type: 'custom:tracker-card'

```

## Debug log

```text

Feb 26 11:17:12 contrib-stretch hass[32011]: 2019-02-26 11:17:12 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Started for /root/.homeassistant/custom_components/alexa_media/__init__.py
Feb 26 11:17:12 contrib-stretch hass[32011]: 2019-02-26 11:17:12 DEBUG (MainThread) [pyupdate.log] CustomComponents(get_local_version) - Parent module '' not loaded, cannot perform relative import
```
