### ISSUE TITLE
Error in my logfile

### ISSUE THREAD

**Issue by Pirol62** [custom-components/custom_updater#127]
## Version of the custom_component

newest version already downloaded
## Describe the bug
I have the following entries in my log:

Traceback (most recent call last):
  File "/config/custom_components/custom_updater.py", line 217, in extra_init
    await self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 222, in cache_versions
    information = await self.pyupdate.get_sensor_data(True)
  File "/config/deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py", line 64, in get_sensor_data
    local_file = self.base_dir + str(component['local_location'])
KeyError: 'local_location'

## `custom_updater` configuration

custom_updater:
  track:
    - components
    - cards
#   - python_scripts
# card_urls:
  component_urls:
# Dev build (unstable)
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/next/custom_components.json
# Released build
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json

```yaml

# Add configuration here

```

## Resources in lovelace configuration

```yaml
resources:
  - type: module
    url: /local/custom-weather-card-chart.js
  - type: module
    url: >-
      /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.2b1
  - type: js
    url: /local/bignumber-card.js?v=1
  - type: module
    url: /customcards/github/custom-cards/tracker-card.js?track=true
# Add configuration here

```

## Tracker-card configuration

```yaml

# Add configuration here

```

## Debug log

```text

Add your logs here.

```
