### ISSUE TITLE
Unable to find services.yaml for the custom_updater integration in 0.92

### ISSUE THREAD

**Issue by kmlucy** [custom-components/custom_updater#131]
## Version of the custom_component
4.2.19

## Describe the bug
Get warning: ``Unable to find services.yaml for the custom_updater integration`` after updating to 0.92.

## `custom_updater` configuration

```yaml
custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/matisaul/vertical-style-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
```

**Comment by callifo** [comment]
Its just missing the service.yaml file. Create a services.yaml file in the folder where custom_updater is, and add the following:

```
check_all:
  description: Check for custom_component updates
install:
  description: Install/Update specified custom_component
update_all:
  description: Update all custom_components
```
