### ISSUE TITLE
Needed: overview for custom_updater... how to/instructions

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#22]
**Is your feature request related to a problem? Please describe.**
a bit of both, no bug!
Since there's not much documentation on rather an important detail, please let me ask here (tried the community, but no response yet)

How to configure the custom_card tracker (on Hassio Non lovelace). 

As of now, I have 2 sensors in the frontend displaying rather unmeaningful states, More-Info is alright.
That is, on the custom component, where I was able to set several components to track.

Not so on the custom_cards.

**Describe the solution you'd like**
Some instruction and examples how to configure

**Describe alternatives you've considered**

What would be really cool: a list of currently available cards and components to simply copy into the configuration. Not that many cards and CC' yet , so hope thats an option?

**Additional context**

![schermafbeelding 2018-09-13 om 16 48 46](https://user-images.githubusercontent.com/33354141/45496080-ed4aed00-b774-11e8-840f-2f673933e403.jpg)
![schermafbeelding 2018-09-13 om 16 48 52](https://user-images.githubusercontent.com/33354141/45496082-ed4aed00-b774-11e8-93a5-cafc2f0da78b.jpg)

```
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
  show_installable: True
```
