### ISSUE TITLE
Change entity states to UTC time instead of timestamp

### ISSUE THREAD

**Issue by pnbruckner** [custom-components/custom_updater#23]
**Is your feature request related to a problem? Please describe.**
Currently the states of sensor.custom_card_tracker and sensor.custom_component_tracker are timestamps, which are not very useful when reading them.

**Describe the solution you'd like**
Using a UTC datetime would be much more useful and consistent with other HA components.

**Describe alternatives you've considered**
None.

**Additional context**
Rather than using `time.time()`, I'd suggest using `homeassistant.util.dt.utcnow()`. Of course, if the timestamp is actually used somewhere (tracker card??), then maybe this can't be done.

**Comment by ludeeus** [comment]
It was in use by the card at some point, but not sure that is the case anymore, will test out different posibilities.
Preferably I would like to not show the time at all, but the number of pending updates

**Comment by pnbruckner** [comment]
Yep, showing the number of pending updates would also be better than the timestamp. In fact, I created a separate template sensor to show that number:
```
sensor:
  - platform: template
    sensors:
      custom_updates:
        friendly_name: Custom updates
        value_template: >
          {{ states.sensor.custom_component_tracker.attributes.values()
             |selectattr('has_update','eq',True)|list|count }}
```
It would be nice not to have to do that.

FWIW, if the tracker card does need the timestamp, maybe it could be made an attribute instead???
