### ISSUE TITLE
Only " ???  Updates" is shown

### ISSUE THREAD

**Issue by claudioita** [custom-components/custom_updater#34]
HASS 0.79.1
```

custom_updater:
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/matisaul/vertical-style-card/master/vertical-style-card.js
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
    - https://raw.githubusercontent.com/rdehuyss
```

```

resources:
   - url: /local/tracker-card.js?v=0.1.5
     type: js
```

2018-09-30 16:52:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 65, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 131, in __init__
    self.cache_versions()
  File "/config/custom_components/custom_updater.py", line 137, in cache_versions
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 47, in get_sensor_data
    cards = get_info_all_cards(custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 15, in get_info_all_cards
    for name, card in response.json().items():
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
