### ISSUE TITLE
custom_updater component not showing current release

### ISSUE THREAD

**Issue by mfabiani53** [custom-components/custom_updater#44]
**Version of the custom_component**

3.1.4
**Describe the bug**
![schermata 2018-10-02 alle 19 55 54](https://user-images.githubusercontent.com/37701688/46373407-462fe600-c68e-11e8-8f56-502643e471e1.png)
As you see the current release is not shown in the frontend and i just downloaded the latest....
**log**

```

**Comment by ludeeus** [comment]
Please sett logging to `debug` and post it here with your configuration for this component

**Comment by mfabiani53** [comment]
Here it is my config about custom_updater:

```
custom_updater:
  show_installable: false
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts
  component_urls: https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-alarm-clock-card/master/custom_updater.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

```
For the logging i don't have any entry, please let me know what to put...
