### ISSUE TITLE
only half of the cards are recognized

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-components/custom_updater#48]
**Version of the custom_component**

**Describe the bug**
Only half of the cards are recognized as being installed, and show in the update window (show_installable: false, so not all are shown by default)

**log**

```
Add your logs here.
```

lovelace resources:

# Lovelace Custom cards
#https://github.com/ciotlosm/custom-lovelace

```
resources:
# https://github.com/custom-cards/tracker-card
# https://github.com/custom-components/custom_updater/wiki/Installation
  - url: /local/custom_ui/lovelace/tracker-card.js?v=0.1.5
    type: js
# https://community.home-assistant.io/t/lovelace-bignumber-card/59280
  - url: /local/custom_ui/lovelace/bignumber-card?v=0.0.1
    type: js
#https://community.home-assistant.io/t/lovelace-attributes-card-entity-row/59122
  - url: /local/custom_ui/lovelace/entity-attributes-card?v=0.0.1
    type: js
# https://community.home-assistant.io/t/lovelace-gauge-card/58880
  - url: /local/custom_ui/lovelace/gauge-card?v=0.1
    type: js
# https://community.home-assistant.io/t/custom-animated-weather-card-for-lovelace/58338
  - url: /local/custom_ui/lovelace/weather-card?v=0.0.1
    type: js
# https://community.home-assistant.io/t/lovelace-bringing-back-entity-filter-monster-card/58701
  - url: /local/custom_ui/lovelace/monster-card?v=0.2.1
    type: js
# https://github.com/kalkih/mini-media-player
# https://community.home-assistant.io/t/lovelace-mini-media-player/68459
  - url: /local/custom_ui/mini-media-player.js?v=0.8.3
    type: module
# https://github.com/matisaul/vertical-style-card
  - url: /local/custom_ui/vertical-style-card.js?v=0.0.2
    type: js
# https://github.com/kuuji/button-card
# https://community.home-assistant.io/t/lovelace-button-card/65981
  - url: /local/custom_ui/button-card.js?v=0.0.2
    type: module
# https://github.com/thomasloven/lovelace-long-press
  - url: /local/custom_ui/long-press.js?v=252428
    type: js
```

custom_updater.yaml

```
# https://github.com/custom-components/custom_updater/wiki/Installation
track:
  - components
  - cards
  - python_scripts

component_urls:
  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json

  - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/custom_components.json

card_urls:
  - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
  - https://raw.githubusercontent.com/matisaul/vertical-style-card/master/tracker.json

  - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/custom_cards.json

python_script_urls:
  - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/python_scripts.json

show_installable: false
```

![schermafbeelding 2018-10-05 om 12 54 02](https://user-images.githubusercontent.com/33354141/46531513-c9735680-c89d-11e8-8941-f54bf3de4f84.jpg)

so not displayed:
bignumber-card
attributes-card
gauge-card
weather-card
monster-card

these cards are shown when I show_installable, but with an n/a version:

![schermafbeelding 2018-10-05 om 15 18 28](https://user-images.githubusercontent.com/33354141/46537638-152ffb00-c8b2-11e8-83a6-78ee4def8ea3.jpg)

weather-card isn't shown at all
