### ISSUE TITLE
Component not found: custom_updater

### ISSUE THREAD

**Issue by woody4165** [custom-components/custom_updater#53]
**Version of the custom_component**
3.1.7
**Describe the bug**
When I add 

```
custom_updater:
  show_installable: true
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts

```
or just:

`custom_updater:
`

I get this error
`Component not found: custom_updater
`

removing it, check is ok.

`custom_updater.py` is in `config/custom_components` folder

What else can I check?

Do I need to make some modification in the python script?

Thanks

**Comment by woody4165** [comment]
I have tried again to add it into `configuraion.yaml`

```
custom_updater:   # https://github.com/custom-components/custom_updater/wiki/Installation
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://github.com/ciotlosm/custom-lovelace/tree/master/thermostat-card/thermostat-card.lib.js
    - https://github.com/ciotlosm/custom-lovelace/tree/master/thermostat-card/thermostat-card.js
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/custom-cards/tracker-card/master/tracker-card.js
    - https://github.com/thomasloven/lovelace-slider-entity-row/blob/master/slider-entity-row.js
    - https://github.com/thomasloven/lovelace-toggle-lock-entity-row/blob/master/toggle-lock-entity-row.js
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
```

and now I don't get any error message during check.

Now I see the card in Lovelace but I don't see anything.

My `ui-lovelace.yaml` is

```
          - type: custom:tracker-card
            title:
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker

```

Should I close this issue or modify the title?

Thanks
