### ISSUE TITLE
Missing info in docs and also adds player?

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/custom_updater#79]
**Version of the custom_component**

Latest
**Describe the bug**
Installed and configured the latest version as per the instructions.

A few issues with new custom updater. 

1. Can’t switch to storage mode until new component loaded otherwise config won’t validate. Should be in the instructions?
2. And cards not in your updater - like the custom-compact-header shit themselves if you change the path - my bad but should be in docs. 
3. Upcoming media card got duplicated one directory level higher instead of staying in it’s configured folder. 
4. I ended up with Thomas Lovens media player as well as the kahlik (?) one
**log**

```
Add your logs here.
```
![image](https://user-images.githubusercontent.com/36390762/52759131-e21b2680-305e-11e9-8b0e-ad65f0855e2d.png)

Note the icon missing from the card title now as well?

Lovelace Config:
```
title: Home
resources:
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /customcards/custom_ui/dark-sky-weather-card.js
    type: module
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/mini-graph-card-bundle.js
    type: module
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.2
    type: module
  - url: /customcards/fold-entity-row.js
    type: js
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/auto-entities.js
    type: js
```
configuration:
```
# Custom Component Updater
custom_updater:
  show_installable: false
  hide_sensor: false
  mode: storage
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
```
