### ISSUE TITLE
HA start takes a minute longer

### ISSUE THREAD

**Issue by VDRainer** [custom-components/custom_updater#84]
**Version of the custom_component**
latest

**Describe the bug**
With the component enabled the HA start takes about 1 minute longer.

**log**
```
2019-02-15 11:22:45 WARNING (MainThread) [homeassistant.setup] Setup of custom_updater is taking over 10 seconds.
```

**Comment by ludeeus** [comment]
Do you see this every time?

**Comment by VDRainer** [comment]
Thanks for your response!
Yes, on every restart.

**Comment by ludeeus** [comment]
That is strange, please share your confirmation and debug logs

**Comment by VDRainer** [comment]
configuration.yaml
```
custom_updater:
  mode: yaml
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    #- https://raw.githubusercontent.com/gurbyz/custom-cards-lovelace/master/custom_updater.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
```
ui-lovelace.yaml
```
resources:
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/gauge-card.js
    type: js
  - url: /customcards/vertical-stack-in-card.js
    type: js
  - url: /customcards/ext-weblink.js
    type: js
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/custom_ui/dark-sky-weather-card.js
    type: module
  - url: /customcards/custom-lovelace/compact-custom-header/compact-custom-header.js
    type: module
  - url: /customcards/simple-thermostat.js
    type: module
  # Thomas Loven
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/browser-commander.js
    type: js
  - url: /customcards/card-modder.js
    type: module
  - url: /customcards/fold-entity-row.js
    type: js
  - url: /customcards/layout-card.js
    type: js
  - url: /customcards/popup-card.js
    type: js
  - url: /customcards/slider-entity-row.js
    type: js
  - url: /customcards/toggle-lock-entity-row.js
    type: js
  - url: /customcards/useful-markdown-card.js
    type: js
  - url: /customcards/lovelace-player.js
    type: js
  - url: /customcards/lovelace-player-config.js
    type: js
  - url: /customcards/state-switch.js
    type: js
  # No custom_update
  - url: /local/power-wheel-card.js?v=0.0.9
    type: module
  - url: /local/secondaryinfo-entity-row.js?v=0.1.0
    type: module
```
[homeassistant-log.zip](https://github.com/custom-components/custom_updater/files/2871071/homeassistant-log.zip)
The delay is from 2019-02-15 23:08:23 to 2019-02-15 23:09:47.

Hope that helps.
Thanks for your effort!
