### ISSUE TITLE
404 when requesting /customcards/*.js

### ISSUE THREAD

**Issue by bbbenji** [custom-components/custom_updater#86]
**Version of the custom_component**
4.0.2

**Describe the bug**
I get a 404 on any request to /customcards/*.js.
`/customcards/button-card.js` does not exist.
`/local/monster-card.js` exists.
Both files are directly in www/

**config**
```
resources:
  - type: js
    url: /customcards/monster-card.js
```
```
logger:
  default: error
  logs:
    custom_components: debug
    pyupdate: debug
custom_updater:
  mode: storage
```

**Home Assistant log**
Debugging enabled, only mention of `custom_updater` in the logs is: 
```
2019-02-15 22:07:11 INFO (SyncWorker_8) [custom_components.custom_updater] if you have ANY issues with this, please report them here: https://github.com/custom-components/custom_updater
2019-02-15 22:07:11 DEBUG (SyncWorker_8) [custom_components.custom_updater] Version 4.0.1
```

**Chrome dev console**
```

Failed to load resource: the server responded with a status of 404 ()                /customcards/button-card.js:1
71087a0064bccad20ddb.chunk.js:282 Uncaught (in promise)                            /customcards/button-card.js
```
