### ISSUE TITLE
Card shows 'player' but it is not on my system

### ISSUE THREAD

**Issue by kloggy** [custom-components/custom_updater#87]
## Version of the customcomponent
custom-updater v4.0.5
tracker-card v0.3.2

## Describe the bug
Item 'player' appears on my card but I do not have this in my config

![image](https://user-images.githubusercontent.com/38220016/52942303-a6d06e80-3362-11e9-98cd-fc0d41407a4e.png)

## `custom_updater` configuration
```
custom_updater:
  show_installable: False
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/ljmerza/waze-card/master/updater.json
```

## Resources in lovelace configuration

```
resources:
  - url: /customcards/custom_ui/tracker-card.js
    type: js
  - url: /customcards/custom_ui/compact-custom-header.js
    type: module
  - url: /customcards/custom_ui/mini-media-player-bundle.js
    type: module
  - url: /customcards/custom_ui/popup-card.js
    type: js
  - url: /customcards/custom_ui/card-tools.js
    type: js
  - url: /customcards/custom_ui/card-modder.js
    type: js
  - url: /customcards/custom_ui/fold-entity-row.js
    type: js
  - url: /customcards/custom_ui/mini-graph-card-bundle.js
    type: module
  - url: /customcards/custom_ui/waze-card.js
    type: js
  - url: /customcards/custom_ui/toggle-lock-entity-row.js
    type: js
  - url: /customcards/custom_ui/browser-commander.js
    type: js
  - url: /customcards/custom_ui/time-input-row.js
    type: js
  - url: /customcards/custom_ui/dark-sky-weather-card.js
    type: module
  # Calendar card
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /customcards/custom_ui/calendar-card.js
    type: module
```
![image](https://user-images.githubusercontent.com/38220016/52942453-f31bae80-3362-11e9-9c97-b91ef02dd065.png)

## Tracker-card configuration
```
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
```
