### ISSUE TITLE
Notification update available

### ISSUE THREAD

**Issue by kugan49** [custom-components/custom_updater#91]
When update is available on a component having a sensor or an event to notify administrator of the system;

**Comment by ludeeus** [comment]
use the sensor it creates to notify your self, it contains the number of pending updates as the state, and has an attribute with the names.

![image](https://user-images.githubusercontent.com/15093472/53174355-eceb3380-35e9-11e9-9525-067cddbd5e7f.png)

**Comment by kugan49** [comment]
THANK YOU

**Comment by advokatb** [comment]
> 
> 
> THANK YOU

Please share you automation when you're done.

**Comment by ludeeus** [comment]
Something like this should work (untested)
```yaml
alias: Custom updates
trigger:
  platfrom: state
  entity_id:
    - sensor.custom_card_tracker
    - sensor.custom_component_tracker
condition:
  condition: template
  value_template: "{{ not is_state(trigger.entity_id, 0) }}"
action:
  service: notify.TARGET
  data_template:
    title: Custom updates aviable!
    message: "There are {{ states(trigger.entity_id) }} update(s) pending, for {{ state_attr(trigger.entity_id, 'has_update') }}"
```

**Comment by kugan49** [comment]
Actually, this is what I've done because trigger template didn't work for me :
```yaml
- alias: "Custom update Notification"
  id: not14
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.custom_card_tracker, sensor.custom_component_tracker
  condition:
    condition: template
    value_template: "{{ ((states.sensor.custom_card_tracker.state | int) > 0) or (states.sensor.custom_component_tracker.state | int) > 0  }}"
#    value_template: "{{ (trigger.to_state | int) > 0 }}"
#   value_template: "{{ trigger.to_state > 0 }}"
#    value_template: "{{ not is_state(trigger.entity_id, 0) }}"
  action:
    service: persistent_notification.create
    data_template:
      title: "Composants Custom - Mise à jour"
      message: |-
        {%- if ((states.sensor.custom_card_tracker.state | int) > 0)-%}
        Il y a {{ states.sensor.custom_card_tracker.state }} mise(s) à jour  de carte disponible :  {{ state_attr('sensor.custom_card_tracker', 'has_update') }}
        {%- endif -%}
        {%- if (((states.sensor.custom_card_tracker.state | int) > 0) and ((states.sensor.custom_card_tracker.state | int) > 0))-%}
        \n
        {%- endif %}
        {%- if ((states.sensor.custom_component_tracker.state | int) > 0)-%}
        Il y a {{ states.sensor.custom_component_tracker.state }} mise(s) à jour  de composents disponible :  {{ state_attr('sensor.custom_component_tracker', 'has_update') }}
        {%- endif -%}


```

**Comment by ludeeus** [comment]
the trigger template will give errors on this trigger:
```yaml
    - platform: homeassistant
      event: start
```
But should work for state

**Comment by pepeEL** [comment]
Anybody can show finally solution ?

**Comment by kugan49** [comment]
> the trigger template will give errors on this trigger:
> 
> ```yaml
>     - platform: homeassistant
>       event: start
> ```
> 
> But should work for state

I tried but it doesn't raise notifications on start of Home assistant

**Comment by kugan49** [comment]
> Anybody can show finally solution ?

My solution work fine : tested

**Comment by pepeEL** [comment]
But can you translate strings in your solution to english ?

**Comment by kugan49** [comment]
here it is :
```yaml
- alias: "Custom update Notification"
  id: not14
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.custom_card_tracker, sensor.custom_component_tracker
  condition:
    condition: template
    value_template: "{{ ((states.sensor.custom_card_tracker.state | int) > 0) or (states.sensor.custom_component_tracker.state | int) > 0  }}"
  action:
    service: persistent_notification.create
    data_template:
      title: "Update Custom Components"
      message: |-
        {%- if ((states.sensor.custom_card_tracker.state | int) > 0)-%}
        There are {{ states.sensor.custom_card_tracker.state }} card update(s) pending, for {{ state_attr('sensor.custom_card_tracker', 'has_update') }}
        {%- endif -%}
        {%- if (((states.sensor.custom_card_tracker.state | int) > 0) and ((states.sensor.custom_card_tracker.state | int) > 0))-%}
        \n
        {%- endif %}
        {%- if ((states.sensor.custom_component_tracker.state | int) > 0)-%}
        There are {{ states.sensor.custom_component_tracker.state }} components  update(s) pending, for {{ state_attr('sensor.custom_component_tracker', 'has_update') }}
        {%- endif -%}
```
