### ISSUE TITLE
[pyupdate.log] CustomCards(yaml_resources) - Lovelace config in yaml file not found

### ISSUE THREAD

**Issue by madrose** [custom-components/custom_updater#93]
When trying to track the custom card used in lovelace default interface (no lovelace.yaml is used) an error is showing the cards component will not show in the updater.

![image](https://user-images.githubusercontent.com/6616792/53227839-e071e400-3698-11e9-9c44-ac1108e1ee16.png)

## Version of the custom_component
4.2.5

## Describe the bug

When I added tracking for the custom cards, new error is showing in HA logs and the cards will not show.

## `custom_updater` configuration
```
  track:
    - components
    - python_scripts
    - cards
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
    - https://raw.githubusercontent.com/vpnmaster/homeassistant-custom-components/master/custom_components.json
    - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/custom_components.json 
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
```

## Resources in lovelace configuration

```
resources:
  - url: /local/surveillance-card.js?v=0
    type: module
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module
```

## Tracker-card configuration

```
title: null
type: 'custom:tracker-card'
trackers:
  - sensor.custom_card_tracker
  - sensor.custom_component_tracker
# Add configuration here

```

## HA logs

```
Feb 22 11:12:25 homeassistant hass[15885]: 2019-02-22 11:12:25 ERROR (MainThread) [pyupdate.log] CustomCards(yaml_resources) - Lovelace config in yaml file not found
Feb 22 11:12:26 homeassistant hass[15885]: 2019-02-22 11:12:26 ERROR (MainThread) [pyupdate.log] CustomCards(yaml_resources) - Lovelace config in yaml file not found


```
